### ISSUE TITLE
Plan on upgrading to sentry/sentry 2.0

### ISSUE THREAD

**Issue by jtraulle** [Connehito/cake-sentry#10]
Hello,

Again, thanks for this excellent plugin :two_hearts: 
I just saw that sentry released their 2.0 version
https://github.com/getsentry/sentry-php/releases/tag/2.0.0

Do you plan to upgrade the cakephp plugin to make use of the new api ?

https://github.com/getsentry/sentry-php/blob/master/UPGRADE-2.0.md

Thanks :slightly_smiling_face:

**Comment by o0h** [comment]
Thank you for your reporting! ✨ 
Yes, cake-sentry will be bumped up to **version 2.0** and it requires `sentry/sdk` 2.x.(both of 2.0 & 2.x-latest.)

I'm willing to carry it out by the end of this month 🚀

**Comment by o0h** [comment]
sorry for the delay!
I'm working on it, and will finish implements and testing in this weekend.
After it, if there aren't any problems, I probably can release new version cake-sentry:2.0 til  next week 👍

**Comment by jtraulle** [comment]
Seems like you are under high load of work @o0h :grin:

**Comment by jtraulle** [comment]
Hello @o0h ,

Hope you are fine :wink: 
Have you had a chance to make progress on this ?

**Comment by o0h** [comment]
I’m sorry to have kept you waiting and thank you for your patience.
Recently I was working on [cakephp-master-replica](https://packagist.org/packages/connehito/cakephp-master-replica) and have done it in last week.

I resume my work to apply sentry-sdk v2.
Please wait a little more 🚀

**Comment by jtraulle** [comment]
Thanks for replying, this is great !
I will definitely have a look at [cakephp-master-replica](https://packagist.org/packages/connehito/cakephp-master-replica) in the meantime 🙂

**Comment by o0h** [comment]
DONE!
please try it out and give us your feedback.
