### ISSUE TITLE
CakePHP 4 support

### ISSUE THREAD

**Issue by BGehrels** [Connehito/cake-sentry#25]
It would be great if the plugin would support CakePHP 4

**Comment by dorxy** [comment]
I've attempted to upgrade to 4.x (tests passing).

Would be nice if other people tested if the fork works. Will do so myself in the upcoming days.

https://github.com/Connehito/cake-sentry/pull/29

**Comment by mfrascati** [comment]
Hi @dorxy, thanks for your work! Any idea about when this can be released?

**Comment by o0h** [comment]
Released 3.0.0 😄 
https://github.com/Connehito/cake-sentry/releases/tag/3.0.0

**Comment by dorxy** [comment]
> Released 3.0.0 😄
> https://github.com/Connehito/cake-sentry/releases/tag/3.0.0

Thanks for the effort guys! 😊👍🏻
