### ISSUE TITLE
Pass returned sentry id to view

### ISSUE THREAD

**Issue by jtraulle** [Connehito/cake-sentry#3]
Hi,

First of all, thanks for this integration of sentry with CakePHP 3.5+ :heart_eyes: 
I was wondering if it will be possible to get back the incident/issue id returned by raven and to pass it to my error view.

Is it possible to do that ? Can you guide me ?

Thanks again :slightly_smiling_face:

**Comment by o0h** [comment]
Thank you for your feedback 😃 

The plugin allows you to inject `send_callback` option to Raven client.
One of the my ideas is receiving last_event_id in send_callback and pass the value via session value.

ex)
```php
// in app.php, setup callback closure for receiving event id from Raven.
'Sentry' => [
    'dsn' => env('SENTRY_DSN'),
        'options' => [
            'send_callback' => function ($data) {
                $request = \Cake\Http\ServerRequestFactory::fromGlobals();
                $session = $request->getSession();
                $session->write('last_event_id', $data['event_id']);
            }
        ],
    ],
];
```

```php
// in ErrorController, set event-id in viewVars.
public function beforeFilter(Event $event)
{
    $sentryLastEventId = $this->request->getSession()->read('last_event_id');
    $this->set('sentry_last_event_id', $sentryLastEventId);
}

// in ErrorTemplate(error400.ctp, error500.ctp or custom elements), echo event-id
<?= $sentry_last_event_id ?>
```

**Comment by jtraulle** [comment]
Many thanks @o0h !
It worked flawlessly :slightly_smiling_face: 

That way, I am able to trigger the [User Feedback](https://docs.sentry.io/learn/user-feedback/) component from Sentry to allow users to submit details about what they were doing before the exception/error. I have also passed ``name`` and ``email`` to my view in ``beforeFilter()`` event to be able to auto-populate name/email from the authenticated user to the Sentry [User Feedback](https://docs.sentry.io/learn/user-feedback/) dialog.

I think these kind of examples could be added in the README :wink: 
I can submit a PR if you don't wan't to do it.

Thanks again :+1:

**Comment by o0h** [comment]
Sorry not to have answered sooner 😢 

I'm glad to hear it went well in its approach.
And to update README.md for `send_callback` hook sounds nice also for me, I'll do it 👍
