### ISSUE TITLE
Compatibility with guzzlehttp/guzzle 7.2.0 ?

### ISSUE THREAD

**Issue by cyberbobjr** [Connehito/cake-sentry#53]
Hi,
many thanks for your job, it's very useful !
Please, could it be possible to let guzzlehttp/guzzle 7.2.0 in required in addition with guzzlehttp/guzzle 6.X ?

Because i use aws/aws-sdk-php and it use guzzlehttp/guzzle 7.2.0.

Many thanks for your help,
Best regards

**Comment by o0h** [comment]
in #57, we will remove dependency on concrete HTTP clients.
This allow you to use the php-http/async-client-implementation library of your choice.
FYI: [README in Sentry SDK for PHP](https://github.com/getsentry/sentry-php#user-content-install:~:text=The%20SDK%20does%20not%20care%20about,package%20that%20provides%20php%2Dhttp%2Fasync%2Dclient%2Dimplementation%20and%20http%2Dmessage%2Dimplementation.)

This change is going to merge as cake-sentry:4.0.
