### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by robertpustulka** [Connehito/cake-sentry#56]
Any plans for PHP 8 upgrade?

This would need an upgrade to Sentry 3.x as well AFAIK

**Comment by robertpustulka** [comment]
Is there a timeline for 4.x?

**Comment by o0h** [comment]
Fixed in #57 and #60

It is already available as 4.0.0-beta1. (If you could give us some feedback I would be very happy!)
We are aiming to release a stable version around a week from now, by the end of this month at the latest.

**Comment by robertpustulka** [comment]
Thanks! I'll give this a try
