### ISSUE TITLE
Release for 4.x

### ISSUE THREAD

**Issue by o0h** [Connehito/cake-sentry#61]
We have released the beta version of the next major version 😄 
https://github.com/Connehito/cake-sentry/releases/tag/4.0.0-beta1

The goals for version 4.0.0 are managed in milestones.
https://github.com/Connehito/cake-sentry/milestone/3

In this issue, we will review the issues and remaining tasks until the official release.

---
The scope of 4.0.0 will include resolution of the following existing issues

- [x] #56
- [x] #53  

The following tasks need to be completed before the stable version can be released 

- [x] Write documents to migration from 3.x to 4.0
- [x] Appropriate amount of behavior verification (in real applications if possible)

any more?

**Comment by scs2771** [comment]
Is there a release date for this? We are hoping to upgrade all of applications to PHP 8 and would love to include this plugin.

**Comment by scs2771** [comment]
Is there anything I can do to help complete this?

**Comment by o0h** [comment]
I'm so sorry for the delay.
All the necessary steps for the release have been completed, and we have just released stable.
I hope you'll give it a try!

**Comment by scs2771** [comment]
Thank you for all the work you have done on this. We will be adding it back to our 4.0 projects this week.
