### ISSUE TITLE
How to enable only in production ?

### ISSUE THREAD

**Issue by HJerem** [Connehito/cake-sentry#7]
I've seen that it's messing up my error config, because when I check if I'm in production or not and disable Cake Sentry in local environment, php is not displaying deprecated messages.

So how is the correct way to do it ?

**Comment by o0h** [comment]
Like DebugKit's way, you can check `debug` value and load the plugin only in development mode.

cf: https://github.com/cakephp/app/blob/7f22a4d6f937c10b4f24f9bd2061657a739902ca/config/bootstrap.php#L215

```php
if (Configure::read('debug')) {
    Plugin::load('DebugKit', ['bootstrap' => true]);
}
```

**Comment by HJerem** [comment]
I did this :

```php
/*
 * Only try to load DebugKit in development mode
 * Debug Kit should not be installed on a production system
 */
if (Configure::read('debug')) {
    $this->addPlugin(\DebugKit\Plugin::class);
} else {
    /*
     * Send errors to Sentry
     */
    $this->addPlugin('Connehito/CakeSentry', ['bootstrap' => true]);
}
```
The problem is, when I'm in local environment with debug mode enabled, I don't have deprecated errors messages anymore.

**Comment by HJerem** [comment]
@o0h Any idea please ?

**Comment by o0h** [comment]
`addPlugin()` is the new style of loading plugin since 3.6.
Sorry, this plugin is not compatible its way yet.
Like described in [README.md](https://github.com/Connehito/cake-sentry/blob/master/README.md), you should call `Plugin::load()` method.

```php
if (!Configure::read('debug')) {
    Plugin::load('Connehito/CakeSentry', ['bootstrap' => true]);
```

@HJerem

**Comment by HJerem** [comment]
@o0h Thanks, it's strange, if I never load your plugin, and when I'm in debug mode, I don't see deprecated warnings...

**Comment by HJerem** [comment]
@o0h Ok it's working now with this code : 

```php
        /*
         * Only try to load DebugKit in development mode
         * Debug Kit should not be installed on a production system
         */
        if (Configure::read('debug')) {
            // disable deprecations panel so that deprecated warnings are shown
            Configure::write('DebugKit.panels', ['DebugKit.Deprecations' => false]);
            $this->addPlugin(\DebugKit\Plugin::class);
        } else {
            /*
             * Send errors to Sentry
             */
            Plugin::load('Connehito/CakeSentry', ['bootstrap' => true]);
        }
```
